2024-07-05 18:04:55,198:ERROR:Error extrayendo datos: [Errno 2] No such file or directory: 'query.sql'
2024-07-05 18:15:17,410:ERROR:Error extrayendo datos: (pyodbc.Error) ('HY090', '[HY090] [Microsoft][Administrador de controladores ODBC] Longitud de cadena o de búfer no válida (0) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-07-05 18:19:40,699:ERROR:Error extrayendo datos: (pyodbc.Error) ('HY090', '[HY090] [Microsoft][Administrador de controladores ODBC] Longitud de cadena o de búfer no válida (0) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-07-05 18:20:01,740:ERROR:Error extrayendo datos: (pyodbc.Error) ('HY090', '[HY090] [Microsoft][Administrador de controladores ODBC] Longitud de cadena o de búfer no válida (0) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-07-05 18:22:19,110:ERROR:Error extrayendo datos: (pyodbc.Error) ('HY090', '[HY090] [Microsoft][Administrador de controladores ODBC] Longitud de cadena o de búfer no válida (0) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-07-05 18:33:50,806:ERROR:Error extrayendo datos: (pyodbc.Error) ('HY090', '[HY090] [Microsoft][Administrador de controladores ODBC] Longitud de cadena o de búfer no válida (0) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-07-05 18:35:00,588:ERROR:Error extrayendo datos: (pyodbc.Error) ('HY090', '[HY090] [Microsoft][Administrador de controladores ODBC] Longitud de cadena o de búfer no válida (0) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-07-05 18:40:23,447:ERROR:Error extrayendo datos: (pyodbc.Error) ('HY090', '[HY090] [Microsoft][Administrador de controladores ODBC] Longitud de cadena o de búfer no válida (0) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-07-05 18:41:11,835:ERROR:Error extrayendo datos: (pyodbc.Error) ('HY090', '[HY090] [Microsoft][Administrador de controladores ODBC] Longitud de cadena o de búfer no válida (0) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-07-05 18:42:32,287:ERROR:Error extrayendo datos: (pyodbc.Error) ('HY090', '[HY090] [Microsoft][Administrador de controladores ODBC] Longitud de cadena o de búfer no válida (0) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-07-05 18:44:31,541:ERROR:Error extrayendo datos: (pyodbc.Error) ('HY090', '[HY090] [Microsoft][Administrador de controladores ODBC] Longitud de cadena o de búfer no válida (0) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-07-05 18:48:49,718:ERROR:Error extrayendo datos: (pyodbc.Error) ('HY090', '[HY090] [Microsoft][Administrador de controladores ODBC] Longitud de cadena o de búfer no válida (0) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-07-05 18:50:28,956:ERROR:Error extrayendo datos: (pyodbc.Error) ('HY090', '[HY090] [Microsoft][Administrador de controladores ODBC] Longitud de cadena o de búfer no válida (0) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-07-05 18:52:06,346:ERROR:Error extrayendo datos: (pyodbc.Error) ('HY090', '[HY090] [Microsoft][Administrador de controladores ODBC] Longitud de cadena o de búfer no válida (0) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-07-05 18:52:52,552:ERROR:Error extrayendo datos: (pyodbc.Error) ('HY090', '[HY090] [Microsoft][Administrador de controladores ODBC] Longitud de cadena o de búfer no válida (0) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-07-05 18:54:44,920:ERROR:Error extrayendo datos: (pyodbc.Error) ('HY090', '[HY090] [Microsoft][Administrador de controladores ODBC] Longitud de cadena o de búfer no válida (0) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-07-05 19:01:06,473:ERROR:Error extrayendo datos: (pyodbc.Error) ('HY090', '[HY090] [Microsoft][Administrador de controladores ODBC] Longitud de cadena o de búfer no válida (0) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-07-05 19:05:54,624:ERROR:Error extrayendo datos: (pyodbc.Error) ('HY090', '[HY090] [Microsoft][Administrador de controladores ODBC] Longitud de cadena o de búfer no válida (0) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-07-05 19:10:45,830:ERROR:Error extrayendo datos: (pyodbc.Error) ('HY090', '[HY090] [Microsoft][Administrador de controladores ODBC] Longitud de cadena o de búfer no válida (0) (SQLExecDirectW)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-07-05 19:13:16,000:INFO:Datos extraidos exitosamente de SQL Server.
2024-07-05 19:14:11,351:INFO:Datos extraidos exitosamente de SQL Server.
2024-07-05 19:19:25,685:ERROR:Error extrayendo datos: module 'credentials' has no attribute 'server'
2024-07-05 19:20:00,383:ERROR:Error extrayendo datos: module 'credentials' has no attribute 'server'
2024-07-05 19:25:40,869:ERROR:Error extrayendo datos: module 'credentials' has no attribute 'server'
2024-07-05 19:27:37,562:ERROR:Error extrayendo datos: module 'Credentials' has no attribute 'server'
2024-07-05 19:28:57,723:ERROR:Error extrayendo datos: module 'Credentials' has no attribute 'server'
2024-07-05 19:33:05,149:INFO:Datos extraidos exitosamente de SQL Server.
2024-07-05 19:34:03,207:INFO:Datos extraidos exitosamente de SQL Server.
2024-07-07 22:23:24,805:INFO:Datos extraidos exitosamente de SQL Server.
2024-07-07 22:23:24,862:INFO:Valores NULL en la columna Response reemplazados por N/A.
2024-07-07 22:23:25,018:INFO:Valores NULL en la columna DataValueFootnoteSymbol reemplazados por N/A.
2024-07-07 22:23:25,120:INFO:Valores NULL en la columna [DataValueFootnote] reemplazados por N/A.
2024-07-07 22:23:25,174:INFO:Valores NULL en la columna [Geolocation] reemplazados por N/A.
2024-07-07 22:26:20,634:INFO:Datos cargados exitosamente
2024-07-09 22:08:13,321:INFO:Datos extraidos exitosamente de SQL Server.
2024-07-09 22:08:13,371:INFO:Valores NULL en la columna Response reemplazados por N/A.
2024-07-09 22:08:13,420:INFO:Valores NULL en la columna DataValueFootnoteSymbol reemplazados por N/A.
2024-07-09 22:08:13,465:INFO:Valores NULL en la columna [DataValueFootnote] reemplazados por N/A.
2024-07-09 22:08:13,514:INFO:Valores NULL en la columna [Geolocation] reemplazados por N/A.
2024-07-09 22:09:19,449:INFO:Datos cargados exitosamente
2024-07-09 22:09:19,449:ERROR:Error creando la base de datos o el modelo dimensional: 'Engine' object has no attribute 'execute'
2024-07-09 22:15:31,109:INFO:Datos extraidos exitosamente de SQL Server.
2024-07-09 22:15:31,119:INFO:Valores NULL en la columna Response reemplazados por N/A.
2024-07-09 22:15:31,144:INFO:Valores NULL en la columna DataValueFootnoteSymbol reemplazados por N/A.
2024-07-09 22:15:31,163:INFO:Valores NULL en la columna [DataValueFootnote] reemplazados por N/A.
2024-07-09 22:15:31,194:INFO:Valores NULL en la columna [Geolocation] reemplazados por N/A.
2024-07-09 22:16:22,930:INFO:Datos cargados exitosamente
2024-07-09 22:16:23,137:INFO:Base de datos DimensionalDB creada exitosamente.
2024-07-09 22:16:23,237:ERROR:Error creando la base de datos o el modelo dimensional: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'GO'. (102) (SQLExecDirectW)")
[SQL: --Crear Modelo Dimensional 

USE DimensionalDB
GO

CREATE TABLE [dbo].[DimLocation] (
    LocationID BIGINT PRIMARY KEY,
    LocationAbbr VARCHAR(MAX),
    LocationDesc VARCHAR(MAX),
    Geolocation VARCHAR(MAX)
);

CREATE TABLE [dbo].[DimTopic] (
    TopicID VARCHAR(MAX) PRIMARY KEY,
    Topic VARCHAR(MAX)
);

CREATE TABLE [dbo].[DimQuestion] (
    QuestionID VARCHAR(MAX) PRIMARY KEY,
    Question VARCHAR(MAX)
);

CREATE TABLE [dbo].[DimStratification] (
    StratificationID1 VARCHAR(MAX) PRIMARY KEY,
    StratificationCategoryID1 VARCHAR(MAX),
    StratificationCategory1 VARCHAR(MAX),
    Stratification1 VARCHAR(MAX)
);

CREATE TABLE [dbo].[DimDataValueType] (
    DataValueTypeID VARCHAR(MAX) PRIMARY KEY,
    DataValueType VARCHAR(MAX)
);

CREATE TABLE [dbo].[FactChronicDiseases] (
    FactID BIGINT IDENTITY(1,1) PRIMARY KEY,
    YearStart BIGINT,
    YearEnd BIGINT,
    DataValue FLOAT,
    DataValueAlt FLOAT,
    LowConfidenceLimit FLOAT,
    HighConfidenceLimit FLOAT,
    DataValueUnit VARCHAR(MAX),
    DataValueFootnote VARCHAR(MAX),
    Response VARCHAR(MAX),
    FOREIGN KEY (LocationID) REFERENCES DimLocation(LocationID),
    FOREIGN KEY (TopicID) REFERENCES DimTopic(TopicID),
    FOREIGN KEY (QuestionID) REFERENCES DimQuestion(QuestionID),
    FOREIGN KEY (StratificationID1) REFERENCES DimStratification(StratificationID1),
    FOREIGN KEY (DataValueTypeID) REFERENCES DimDataValueType(DataValueTypeID)
);
]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-07-09 22:25:04,025:INFO:Datos extraidos exitosamente de SQL Server.
2024-07-09 22:25:04,041:INFO:Valores NULL en la columna Response reemplazados por N/A.
2024-07-09 22:25:04,071:INFO:Valores NULL en la columna DataValueFootnoteSymbol reemplazados por N/A.
2024-07-09 22:25:04,108:INFO:Valores NULL en la columna [DataValueFootnote] reemplazados por N/A.
2024-07-09 22:25:04,134:INFO:Valores NULL en la columna [Geolocation] reemplazados por N/A.
2024-07-09 22:26:04,553:INFO:Datos cargados exitosamente
2024-07-09 22:26:04,553:ERROR:Error creando la base de datos o el modelo dimensional: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Database 'DimensionalDB' already exists. Choose a different database name. (1801) (SQLExecDirectW)")
[SQL: CREATE DATABASE DimensionalDB]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-07-09 22:27:45,490:INFO:Datos extraidos exitosamente de SQL Server.
2024-07-09 22:27:45,490:INFO:Valores NULL en la columna Response reemplazados por N/A.
2024-07-09 22:27:45,534:INFO:Valores NULL en la columna DataValueFootnoteSymbol reemplazados por N/A.
2024-07-09 22:27:45,571:INFO:Valores NULL en la columna [DataValueFootnote] reemplazados por N/A.
2024-07-09 22:27:45,602:INFO:Valores NULL en la columna [Geolocation] reemplazados por N/A.
2024-07-09 22:28:40,736:INFO:Datos cargados exitosamente
2024-07-09 22:28:40,908:INFO:Base de datos DimensionalDB creada exitosamente.
2024-07-09 22:28:41,084:ERROR:Error creando la base de datos o el modelo dimensional: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Column 'TopicID' in table 'DimTopic' is of a type that is invalid for use as a key column in an index. (1919) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Could not create constraint or index. See previous errors. (1750)")
[SQL: CREATE TABLE [dbo].[DimLocation] (
    LocationID BIGINT PRIMARY KEY,
    LocationAbbr VARCHAR(MAX),
    LocationDesc VARCHAR(MAX),
    Geolocation VARCHAR(MAX)
);

CREATE TABLE [dbo].[DimTopic] (
    TopicID VARCHAR(MAX) PRIMARY KEY,
    Topic VARCHAR(MAX)
);

CREATE TABLE [dbo].[DimQuestion] (
    QuestionID VARCHAR(MAX) PRIMARY KEY,
    Question VARCHAR(MAX)
);

CREATE TABLE [dbo].[DimStratification] (
    StratificationID1 VARCHAR(MAX) PRIMARY KEY,
    StratificationCategoryID1 VARCHAR(MAX),
    StratificationCategory1 VARCHAR(MAX),
    Stratification1 VARCHAR(MAX)
);

CREATE TABLE [dbo].[DimDataValueType] (
    DataValueTypeID VARCHAR(MAX) PRIMARY KEY,
    DataValueType VARCHAR(MAX)
);

CREATE TABLE [dbo].[FactChronicDiseases] (
    FactID BIGINT IDENTITY(1,1) PRIMARY KEY,
    YearStart BIGINT,
    YearEnd BIGINT,
    DataValue FLOAT,
    DataValueAlt FLOAT,
    LowConfidenceLimit FLOAT,
    HighConfidenceLimit FLOAT,
    DataValueUnit VARCHAR(MAX),
    DataValueFootnote VARCHAR(MAX),
    Response VARCHAR(MAX),
    FOREIGN KEY (LocationID) REFERENCES DimLocation(LocationID),
    FOREIGN KEY (TopicID) REFERENCES DimTopic(TopicID),
    FOREIGN KEY (QuestionID) REFERENCES DimQuestion(QuestionID),
    FOREIGN KEY (StratificationID1) REFERENCES DimStratification(StratificationID1),
    FOREIGN KEY (DataValueTypeID) REFERENCES DimDataValueType(DataValueTypeID)
);]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-07-09 22:33:25,346:INFO:Datos extraidos exitosamente de SQL Server.
2024-07-09 22:33:25,366:INFO:Valores NULL en la columna Response reemplazados por N/A.
2024-07-09 22:33:25,404:INFO:Valores NULL en la columna DataValueFootnoteSymbol reemplazados por N/A.
2024-07-09 22:33:25,437:INFO:Valores NULL en la columna [DataValueFootnote] reemplazados por N/A.
2024-07-09 22:33:25,496:INFO:Valores NULL en la columna [Geolocation] reemplazados por N/A.
2024-07-09 22:34:12,254:INFO:Datos cargados exitosamente
2024-07-09 22:34:12,457:INFO:Base de datos DimensionalDB creada exitosamente.
2024-07-09 22:34:12,569:INFO:Modelo dimensional creado exitosamente.
2024-07-09 22:38:11,682:INFO:Datos extraidos exitosamente de SQL Server.
2024-07-09 22:38:11,722:INFO:Valores NULL en la columna Response reemplazados por N/A.
2024-07-09 22:38:11,766:INFO:Valores NULL en la columna DataValueFootnoteSymbol reemplazados por N/A.
2024-07-09 22:38:11,816:INFO:Valores NULL en la columna [DataValueFootnote] reemplazados por N/A.
2024-07-09 22:38:11,866:INFO:Valores NULL en la columna [Geolocation] reemplazados por N/A.
2024-07-09 22:38:57,779:INFO:Datos cargados exitosamente
2024-07-09 22:38:57,952:INFO:Base de datos DimensionalDB creada exitosamente.
2024-07-09 22:38:58,062:INFO:Modelo dimensional creado exitosamente.
2024-07-09 22:41:22,678:INFO:Datos extraidos exitosamente de SQL Server.
2024-07-09 22:41:22,694:INFO:Valores NULL en la columna Response reemplazados por N/A.
2024-07-09 22:41:22,727:INFO:Valores NULL en la columna DataValueFootnoteSymbol reemplazados por N/A.
2024-07-09 22:41:22,750:INFO:Valores NULL en la columna [DataValueFootnote] reemplazados por N/A.
2024-07-09 22:41:22,794:INFO:Valores NULL en la columna [Geolocation] reemplazados por N/A.
2024-07-09 22:42:14,618:INFO:Datos cargados exitosamente
2024-07-09 22:42:15,727:INFO:Base de datos DimensionalDB creada exitosamente.
2024-07-09 22:42:15,863:INFO:Modelo dimensional creado exitosamente.
2024-07-09 22:45:37,853:INFO:Datos extraidos exitosamente de SQL Server.
2024-07-09 22:45:37,871:INFO:Valores NULL en la columna Response reemplazados por N/A.
2024-07-09 22:45:37,898:INFO:Valores NULL en la columna DataValueFootnoteSymbol reemplazados por N/A.
2024-07-09 22:45:37,931:INFO:Valores NULL en la columna [DataValueFootnote] reemplazados por N/A.
2024-07-09 22:45:37,962:INFO:Valores NULL en la columna [Geolocation] reemplazados por N/A.
2024-07-09 22:46:23,114:INFO:Datos cargados exitosamente
2024-07-09 22:46:23,294:INFO:Base de datos DimensionalDB creada exitosamente.
2024-07-09 22:46:23,434:INFO:Modelo dimensional creado exitosamente.
2024-07-09 22:49:51,518:INFO:Datos cargados exitosamente en DimLocation.
2024-07-09 22:49:52,687:INFO:Datos cargados exitosamente en DimTopic.
2024-07-09 22:49:54,325:INFO:Datos cargados exitosamente en DimQuestion.
2024-07-09 22:49:56,632:INFO:Datos cargados exitosamente en DimStratification.
2024-07-09 22:49:57,844:INFO:Datos cargados exitosamente en DimDataValueType.
2024-07-09 23:00:22,297:INFO:Datos extraidos exitosamente de SQL Server.
2024-07-09 23:00:22,312:INFO:Valores NULL en la columna Response reemplazados por N/A.
2024-07-09 23:00:22,348:INFO:Valores NULL en la columna DataValueFootnoteSymbol reemplazados por N/A.
2024-07-09 23:00:22,380:INFO:Valores NULL en la columna [DataValueFootnote] reemplazados por N/A.
2024-07-09 23:00:22,415:INFO:Valores NULL en la columna [Geolocation] reemplazados por N/A.
2024-07-09 23:01:09,444:INFO:Datos cargados exitosamente
2024-07-09 23:03:48,597:INFO:Datos extraidos exitosamente de SQL Server.
2024-07-09 23:03:48,597:INFO:Valores NULL en la columna Response reemplazados por N/A.
2024-07-09 23:03:48,640:INFO:Valores NULL en la columna DataValueFootnoteSymbol reemplazados por N/A.
2024-07-09 23:03:48,675:INFO:Valores NULL en la columna [DataValueFootnote] reemplazados por N/A.
2024-07-09 23:03:48,716:INFO:Valores NULL en la columna [Geolocation] reemplazados por N/A.
2024-07-09 23:04:34,358:INFO:Datos cargados exitosamente
2024-07-09 23:04:34,374:ERROR:Error Creando modelo dimensional: (pyodbc.OperationalError) ('08004', "[08004] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Database 'DimensionalDB' does not exist. Make sure that the name is entered correctly. (911) (SQLExecDirectW)")
[SQL: 
    -- Crear Modelo Dimensional
    CREATE DATABASE DimensionalDB

    USE DimensionalDB;
    GO

    CREATE TABLE [dbo].[DimLocation] (
        LocationID BIGINT PRIMARY KEY,
        LocationAbbr VARCHAR(100),
        LocationDesc VARCHAR(255),
        Geolocation VARCHAR(255)
    );

    CREATE TABLE [dbo].[DimTopic] (
        TopicID VARCHAR(50) PRIMARY KEY,
        Topic VARCHAR(255)
    );

    CREATE TABLE [dbo].[DimQuestion] (
        QuestionID VARCHAR(50) PRIMARY KEY,
        Question VARCHAR(255)
    );

    CREATE TABLE [dbo].[DimStratification] (
        StratificationID1 VARCHAR(50) PRIMARY KEY,
        StratificationCategoryID1 VARCHAR(50),
        StratificationCategory1 VARCHAR(255),
        Stratification1 VARCHAR(255)
    );

    CREATE TABLE [dbo].[DimDataValueType] (
        DataValueTypeID VARCHAR(50) PRIMARY KEY,
        DataValueType VARCHAR(255)
    );

    CREATE TABLE [dbo].[FactChronicDiseases] (
        FactID BIGINT IDENTITY(1,1) PRIMARY KEY,
        YearStart BIGINT,
        YearEnd BIGINT,
        DataValue FLOAT,
        DataValueAlt FLOAT,
        LowConfidenceLimit FLOAT,
        HighConfidenceLimit FLOAT,
        DataValueUnit VARCHAR(255),
        DataValueFootnote VARCHAR(255),
        Response VARCHAR(255),
        LocationID BIGINT,
        TopicID VARCHAR(50),
        QuestionID VARCHAR(50),
        StratificationID1 VARCHAR(50),
        DataValueTypeID VARCHAR(50),
        FOREIGN KEY (LocationID) REFERENCES DimLocation(LocationID),
        FOREIGN KEY (TopicID) REFERENCES DimTopic(TopicID),
        FOREIGN KEY (QuestionID) REFERENCES DimQuestion(QuestionID),
        FOREIGN KEY (StratificationID1) REFERENCES DimStratification(StratificationID1),
        FOREIGN KEY (DataValueTypeID) REFERENCES DimDataValueType(DataValueTypeID)
    );
    ]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-07-09 23:09:13,510:INFO:Datos extraidos exitosamente de SQL Server.
2024-07-09 23:09:13,526:INFO:Valores NULL en la columna Response reemplazados por N/A.
2024-07-09 23:09:13,556:INFO:Valores NULL en la columna DataValueFootnoteSymbol reemplazados por N/A.
2024-07-09 23:09:13,586:INFO:Valores NULL en la columna [DataValueFootnote] reemplazados por N/A.
2024-07-09 23:09:13,622:INFO:Valores NULL en la columna [Geolocation] reemplazados por N/A.
2024-07-09 23:09:58,993:INFO:Datos cargados exitosamente
2024-07-09 23:09:59,008:ERROR:Error Creando modelo dimensional: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]CREATE DATABASE statement not allowed within multi-statement transaction. (226) (SQLExecDirectW)')
[SQL: CREATE DATABASE DimensionalDB]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-07-09 23:11:41,624:INFO:Datos extraidos exitosamente de SQL Server.
2024-07-09 23:11:41,646:INFO:Valores NULL en la columna Response reemplazados por N/A.
2024-07-09 23:11:41,684:INFO:Valores NULL en la columna DataValueFootnoteSymbol reemplazados por N/A.
2024-07-09 23:11:41,721:INFO:Valores NULL en la columna [DataValueFootnote] reemplazados por N/A.
2024-07-09 23:11:41,768:INFO:Valores NULL en la columna [Geolocation] reemplazados por N/A.
2024-07-09 23:12:26,630:INFO:Datos cargados exitosamente
2024-07-09 23:12:26,833:INFO:Base de datos DimensionalDB creada exitosamente.
2024-07-09 23:12:26,927:ERROR:Error creando la base de datos o el modelo dimensional: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'GO'. (102) (SQLExecDirectW)")
[SQL: -- Crear Modelo Dimensional
CREATE DATABASE DimensionalDB

USE DimensionalDB;
GO

CREATE TABLE [dbo].[DimLocation] (
    LocationID BIGINT PRIMARY KEY,
    LocationAbbr VARCHAR(100),
    LocationDesc VARCHAR(255),
    Geolocation VARCHAR(255)
);

CREATE TABLE [dbo].[DimTopic] (
    TopicID VARCHAR(50) PRIMARY KEY,
    Topic VARCHAR(255)
);

CREATE TABLE [dbo].[DimQuestion] (
    QuestionID VARCHAR(50) PRIMARY KEY,
    Question VARCHAR(255)
);

CREATE TABLE [dbo].[DimStratification] (
    StratificationID1 VARCHAR(50) PRIMARY KEY,
    StratificationCategoryID1 VARCHAR(50),
    StratificationCategory1 VARCHAR(255),
    Stratification1 VARCHAR(255)
);

CREATE TABLE [dbo].[DimDataValueType] (
    DataValueTypeID VARCHAR(50) PRIMARY KEY,
    DataValueType VARCHAR(255)
);

CREATE TABLE [dbo].[FactChronicDiseases] (
    FactID BIGINT IDENTITY(1,1) PRIMARY KEY,
    YearStart BIGINT,
    YearEnd BIGINT,
    DataValue FLOAT,
    DataValueAlt FLOAT,
    LowConfidenceLimit FLOAT,
    HighConfidenceLimit FLOAT,
    DataValueUnit VARCHAR(255),
    DataValueFootnote VARCHAR(255),
    Response VARCHAR(255),
    LocationID BIGINT,
    TopicID VARCHAR(50),
    QuestionID VARCHAR(50),
    StratificationID1 VARCHAR(50),
    DataValueTypeID VARCHAR(50),
    FOREIGN KEY (LocationID) REFERENCES DimLocation(LocationID),
    FOREIGN KEY (TopicID) REFERENCES DimTopic(TopicID),
    FOREIGN KEY (QuestionID) REFERENCES DimQuestion(QuestionID),
    FOREIGN KEY (StratificationID1) REFERENCES DimStratification(StratificationID1),
    FOREIGN KEY (DataValueTypeID) REFERENCES DimDataValueType(DataValueTypeID)
);
]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-07-09 23:13:58,829:INFO:Datos extraidos exitosamente de SQL Server.
2024-07-09 23:13:58,829:INFO:Valores NULL en la columna Response reemplazados por N/A.
2024-07-09 23:13:58,867:INFO:Valores NULL en la columna DataValueFootnoteSymbol reemplazados por N/A.
2024-07-09 23:13:58,905:INFO:Valores NULL en la columna [DataValueFootnote] reemplazados por N/A.
2024-07-09 23:13:58,935:INFO:Valores NULL en la columna [Geolocation] reemplazados por N/A.
2024-07-09 23:14:51,737:INFO:Datos cargados exitosamente
2024-07-09 23:14:51,926:INFO:Base de datos DimensionalDB creada exitosamente.
2024-07-09 23:14:52,020:ERROR:Error creando la base de datos o el modelo dimensional: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'GO'. (102) (SQLExecDirectW)")
[SQL: -- Crear Modelo Dimensional

USE DimensionalDB;
GO

CREATE TABLE [dbo].[DimLocation] (
    LocationID BIGINT PRIMARY KEY,
    LocationAbbr VARCHAR(100),
    LocationDesc VARCHAR(255),
    Geolocation VARCHAR(255)
);

CREATE TABLE [dbo].[DimTopic] (
    TopicID VARCHAR(50) PRIMARY KEY,
    Topic VARCHAR(255)
);

CREATE TABLE [dbo].[DimQuestion] (
    QuestionID VARCHAR(50) PRIMARY KEY,
    Question VARCHAR(255)
);

CREATE TABLE [dbo].[DimStratification] (
    StratificationID1 VARCHAR(50) PRIMARY KEY,
    StratificationCategoryID1 VARCHAR(50),
    StratificationCategory1 VARCHAR(255),
    Stratification1 VARCHAR(255)
);

CREATE TABLE [dbo].[DimDataValueType] (
    DataValueTypeID VARCHAR(50) PRIMARY KEY,
    DataValueType VARCHAR(255)
);

CREATE TABLE [dbo].[FactChronicDiseases] (
    FactID BIGINT IDENTITY(1,1) PRIMARY KEY,
    YearStart BIGINT,
    YearEnd BIGINT,
    DataValue FLOAT,
    DataValueAlt FLOAT,
    LowConfidenceLimit FLOAT,
    HighConfidenceLimit FLOAT,
    DataValueUnit VARCHAR(255),
    DataValueFootnote VARCHAR(255),
    Response VARCHAR(255),
    LocationID BIGINT,
    TopicID VARCHAR(50),
    QuestionID VARCHAR(50),
    StratificationID1 VARCHAR(50),
    DataValueTypeID VARCHAR(50),
    FOREIGN KEY (LocationID) REFERENCES DimLocation(LocationID),
    FOREIGN KEY (TopicID) REFERENCES DimTopic(TopicID),
    FOREIGN KEY (QuestionID) REFERENCES DimQuestion(QuestionID),
    FOREIGN KEY (StratificationID1) REFERENCES DimStratification(StratificationID1),
    FOREIGN KEY (DataValueTypeID) REFERENCES DimDataValueType(DataValueTypeID)
);
]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-07-09 23:15:58,793:INFO:Datos extraidos exitosamente de SQL Server.
2024-07-09 23:15:58,793:INFO:Valores NULL en la columna Response reemplazados por N/A.
2024-07-09 23:15:58,828:INFO:Valores NULL en la columna DataValueFootnoteSymbol reemplazados por N/A.
2024-07-09 23:15:58,862:INFO:Valores NULL en la columna [DataValueFootnote] reemplazados por N/A.
2024-07-09 23:15:58,895:INFO:Valores NULL en la columna [Geolocation] reemplazados por N/A.
2024-07-09 23:16:47,587:INFO:Datos cargados exitosamente
2024-07-09 23:16:47,775:INFO:Base de datos DimensionalDB creada exitosamente.
2024-07-09 23:16:47,884:INFO:Modelo dimensional creado exitosamente.
